### ISSUE TITLE
First sticky header is not updated when data is changed

### ISSUE THREAD

**Issue by todorone** [Shopify/flash-list#814]
## Current behavior

When we update data of list with sticky headers, the first one(that is currently sticky) is not updated, while the rest is updated.

## Expected behavior

Items are updated when data is changed

## To Reproduce

https://snack.expo.dev/@todorone/flashlist-sticky-headers-bug

- We have 2 header items A and D.
- Pressing "SWAP"
- Headers items should be B and C, instead we see A and C
- When scrolled up/down, items are rendered correctly and we see B and C

## Platform:

- [x] iOS
- [x] Android

## Environment

1.3.1

**Comment by BuqiLiao** [comment]
A better way to fix this rather than updating the `key` prop to cause flashing is to add a fake header and increase the stickyHeaderIndices:
`  const renderItem = ({ item }) => {
    if(item === "FAKE_HEADER") return null;
    if (typeof item === "string") {
      return <MyChatSectionHeader title={item} />;
    }
    return <MyChatItem
      item={item}
      navigation={navigation}
    />
  };
  const stickyHeaderIndices = myChats
    .map((item, index) => (typeof item === "string" ? index+1 : null))
    .filter(index => index !== null);

  <FlashList
    data={["FAKE_HEADER", ...myChats]}
    renderItem={renderItem}
    keyExtractor={item => typeof item === "string" ? item : item._id}
    onEndReached={loadMoreChatsHandler}
    onEndReachedThreshold={0.05}
    ListFooterComponent={<LoadingMoreFooter isLoadingMore={isLoadingMore} />}
    stickyHeaderIndices={stickyHeaderIndices}
    getItemType={item => typeof item === "string" ? "sectionHeader" : "row"}
    estimatedItemSize={70}
  />
` 
However, there will be a slight shake if you scroll up the list since the fake header's indices is counted

**Comment by BuqiLiao** [comment]
I just found a ever better solution without even slight shaking:
Try to increase the indices once and immediately change back to origin:
```js
  const [stickyIndices, setStickyIndices] = useState([]);
  useEffect(() => {
    const getStickyIndices = (number=0) => {
      return myChats
      .map((item, index) => (typeof item === "string" ? index+number : null))
      .filter(index => index !== null);
    }
    setStickyIndices(getStickyIndices(1));
    setTimeout(() => {
      setStickyIndices(getStickyIndices(0));
    }, 100);
  }, [myChats.length]);
  <FlashList
    data={myChats}
    renderItem={renderItem}
    keyExtractor={item => typeof item === "string" ? item : item._id}
    onEndReached={loadMoreChatsHandler}
    onEndReachedThreshold={0.05}
    ListFooterComponent={<LoadingMoreFooter isLoadingMore={isLoadingMore} />}
    stickyHeaderIndices={stickyIndices}
    getItemType={item => typeof item === "string" ? "sectionHeader" : "row"}
    estimatedItemSize={70}
  />
```
After all, those are temporary solutions, hope someone could make a PR for this

**Comment by itajenglish** [comment]
+1

**Comment by bryanltobing** [comment]
this issue is still exist

**Comment by domenvilar** [comment]
I have the same problem. First sticky header is not updated when the data changes.

**Comment by dpatterson414** [comment]
+1

**Comment by MoeKanan** [comment]
+1

**Comment by pmj100** [comment]
+1

**Comment by switz** [comment]
Yeah, honestly seeing a lot of bugs tied directly to `stickyHeaderIndices` unfortunately

**Comment by MikeKovarik** [comment]
+1

**Comment by victorlucss** [comment]
+1

**Comment by GollyJer** [comment]
Does this have an official fix in the works?

**Comment by DTupalov** [comment]
What is the status of this issue? I see that the PR is ready. When do you plan to release it?

**Comment by charlie-nis** [comment]
@pehagg 

> As a simpler workaround, use `Array` for the sticky headers, e.g.
> 
>   const stickyHeaderIndices = new Array(...);
> This will force the FlashList to detect the change. No need for `useState` hooks or `setTimeOut`.
> 
> edit: posted this solution a little too prematurely. This will re-render the first item, but the item is no longer sticky. Sigh. edit2: this seems to work after all, I had a bug in my code that didn't set the first item as a sticky header

your solution works beautifully

 const stickyIndices: number[] = new Array(
    ...resultsItems
      .map((item, index) => {
        if (typeof item === "string") {
          return index;
        } else {
          return null;
        }
      })
      .filter((item) => item !== null)
  );

**Comment by DTupalov** [comment]
I see that PR #1267 has been merged into the main branch, and that’s awesome! :)
When do you plan to release this fix?

Thanks for the response.

**Comment by dkumar-carfax** [comment]
Still facing this issue in Android, Is there any update on this to be released?

**Comment by cam-shaw** [comment]
@DTupalov @dkumar-carfax have you both tested on version 1.7.2?

**Comment by peterjskaltsis** [comment]
This seems fixed on 1.7.2 for me

**Comment by pehagg** [comment]
This is _not_ fixed in 1.7.2.

**Comment by anhkieet** [comment]
Facing the same issue, has anyone had any solutions?

**Comment by amerdiglisic-aily** [comment]
> This is _not_ fixed in 1.7.2.
> 
> edit: additional info: the header _is_ updated in case it's _not_ in the "sticky mode", but if it is, it doesn't update. See attached video clip.
> 
>  ScreenRecording_12-03-2024.15-58-48_1.mov

I have the same behavior still.

**Comment by SumitR9910** [comment]
Still facing the same issue after updating to 1.7.2, passing the extraData prop can be a possible solution but does not seem to work for me on android (not yet tested on iOS).

**Comment by soonoo** [comment]
I couldn't find any other way except rendering one more header and controlling its stickiness directly based on the viewableItems index.
```tsx
const [showStickyHeader, setShowStickyHeaer] = useState(false); 

<FlashList
  onViewableItemsChanged={({ viewableItems }) => {
    if (typeof viewableItems[0]?.index === "number") {
      setShowStickyHeader(viewableItems[0]?.index > 2);
    }
  }}
/>
{showStickyHeader && <Header style={{ position: "absolute", top: 0 }} />}
```

**Comment by huix9527** [comment]
> This seems fixed on 1.7.2 for me

Not fixed on 1.7.3, sticky headers still don't update. The `new Array` hack works for me though.
